#!/bin/bash
# kctx
#
# Set current context ($KUBECONFIG).

# Explicit: use param from command-line.
if [ "$1" = "-e" ] ; then
    kubectl config use-context "$2"
    exit
fi

header=$(kubectl config get-contexts | head -1 | cut -c11-)

kubectl config get-contexts --no-headers | cut -c11- | sort\
    | fzf +m --no-sort --header="${header}" --height=40% -n1 --prompt="context > " \
    | awk '{print $1}' \
    | xargs --no-run-if-empty kubectl config use-context
# cut -c11- : column 'CURRENT' must be removed; counts as 1 field when 
#       has '*' and 0 fields otherwise.
