#!/bin/bash
# kns
#
# Set default namespace in current context ($KUBECONFIG).

if [ "$1" = "-e" ] ; then
    kubectl config set-context "$(kubectl config current-context)" \
        --namespace "$2"
else
  kubectl get ns \
      | fzf --header-lines=1 --height=40% --prompt="$(kubectl config current-context):namespace > " \
      | awk '{print $1}' \
      | xargs --no-run-if-empty \
          kubectl config set-context "$(kubectl config current-context)" --namespace
fi
